INDO_PROVINCES = ['Bali',
'Jakarta',
'Special Region of Yogyakarta',
'Papua',
'West Java',
'East Java',
'Central Java',
'Acehdiv',
'Lampungdiv',
'East Kalimantan',
'Jambidiv',
'South Sumatra',
'West Papua',
'Bantendiv',
'North Sumatra',
'Riaudiv',
'West Sumatra',
'South Sulawesi',
'West Kalimantan',
'South Kalimantan',
'East Nusa Tenggara',
'Riau Islands',
'Central Kalimantan',
'North Sulawesi',
'Bengkulu',
'West Nusa Tenggara',
'Malukudiv',
'Central Sulawesi',
'Southeast Sulawesi',
'Bangka-Belitung Islands',
'Gorontalo',
'West Sulawesi',
'North Maluku']